core = "7.x"
api = "2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"
projects[token][subdir] = "contrib"
projects[token][version] = "1.5"
projects[entity][subdir] = "contrib"
projects[entitycache][subdir] = "contrib"
projects[jquery_update][subdir] = "contrib"
projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"
